### ISSUE TITLE
Jakarta inject API jar classes are not Java 8 byte code.

### ISSUE THREAD

**Issue by jhanders34** [eclipse-ee4j/injection-api#18] opened 2021-01-28 20:30 UTC
**Describe the bug**
The classes in the jakarta.inject api JAR have Java 5 byte code instead of Java 8 byte code.

**To Reproduce**
javap -v -classpath jakarta.inject-api-2.0.0.jar jakarta.inject.Inject | grep "major version"
  major version: 49
javap -v -classpath jakarta.inject-api-2.0.0.jar jakarta.inject.Named | grep "major version"
  major version: 49
javap -v -classpath jakarta.inject-api-2.0.0.jar jakarta.inject.Provider | grep "major version"
  major version: 49
javap -v -classpath jakarta.inject-api-2.0.0.jar jakarta.inject.Qualifier | grep "major version"
  major version: 49
javap -v -classpath jakarta.inject-api-2.0.0.jar jakarta.inject.Scope | grep "major version"
  major version: 49
javap -v -classpath jakarta.inject-api-2.0.0.jar jakarta.inject.Singleton | grep "major version"
  major version: 49

**Expected behavior**
Jakarta EE 9's minimum Java level is Java 8.  As such all API jars should have Java 8 byte code.  All other API JARs for the Jakarta EE 9 features have classes with Java 8 byte code.  As you see above the major version is 49.  It should be 52 for Java 8 byte code.

**Additional context**
From looking at other projects, the following needs to configured in the pom.xml
```
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
```

**Comment by kwsutter** [comment] 2021-01-28 20:32
Could we get this updated in a 2.0.1 release of the API?

**Comment by pzygielo** [comment] 2021-01-28 22:02
@jhanders34 could you elaborate on the bug a bit?
I don't understand what the problem is. AFAIU having earlier byte code version is fine, and Jakarta EE9 shall be AT MOST at level of 8.

**Comment by jhanders34** [comment] 2021-01-28 23:10
@pzygielo last year I attended a Jakarta 9 meeting and I asked about the statement that Java 8 would be the minimum level that would be supported.  This was at the time when there was debate on whether the minimum Java level would be 8 or 11.  At the time it was decided to be Java 8.  The question I asked was whether with that decision would the byte code of the API jars also be Java 8 byte code.  I was told yes that was what should be done.  For some additional context, in the past Java / Jakarta EE API jars had a mix of different Java byte levels.  Newer Java versions have optimizations depending on the byte code level of the classes that are loaded.  Also as I said in the description the injection API jar is the odd API jar out; it is the only one that isn't using Java 8 byte code.  A change to use Java 8 byte code would create consistency.  I hope that helps give reason why I wrote this issue.

**Comment by jhanders34** [comment] 2021-02-11 18:47
@pzygielo Any additional thoughts on this?

**Comment by starksm64** [comment] 2021-02-11 19:01
Classes that are usable on Java 8 is the minimum requirement, meaning that Java 9 or later are not supported. There was no requirement to have API jars compiled at the Java 8 level byte code, major.version=52. 

I'll update the pom to use Java 8 source and target levels. It will be a question to the spec committee as to whether this is a sufficient reason for a 2.0.1 service release.

**Comment by rbygrave** [comment] 2021-10-04 21:33
Just to note that this issue is resolved by commit - https://github.com/eclipse-ee4j/injection-api/commit/749c66a94f7e78d1f679123378acc605a4aa7463

**Comment by jhanders34** [comment] 2021-10-04 21:44
Will there be a 2.0.1 version of the injection-api created?

**Comment by Ladicek** [comment] 2021-10-05 07:07
Yea I think we should do a 2.0.1 with recent changes (module-info.class). Not sure if there is any specific "bureaucracy" involved in producing a final release... but with recent changes to the release jobs, we should probably do an RC first anyway :-)

**Comment by starksm64** [comment] 2021-10-05 13:06
This needs to be verified by running the injection TCK against weld before the release is pushed out. For service releases like this, there is no requirement for approval by the spec committee.

**Comment by Ladicek** [comment] 2021-10-05 13:31
OK cool. That said, I think the best way to test this with Weld would be to do an RC release :-)

**Comment by starksm64** [comment] 2021-10-05 13:35
True, so I'll do that as I believe there has to be a release of the TCK to match any updates to the API jar as per the TCK process guide, but I have to look that up. An RC can be put out independently.

**Comment by Ladicek** [comment] 2021-10-05 13:37
We can discuss that on the call in 20 minutes, I'd be interested to know the requirements around a final release.

**Comment by starksm64** [comment] 2021-10-05 14:12
It has been staged and released to maven central. It is available from staging repo here, central will be available soon:
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/inject/jakarta.inject-api/2.0.1.RC1/

**Comment by rbygrave** [comment] 2021-10-05 20:28
Awesome, thanks Scott. I note the tag "release notes" at https://github.com/eclipse-ee4j/injection-api/releases/tag/2.0.1.RC1  haven't been updated yet but maybe that happens at a later point.  FYI: My tests all passing with 2.0.1.RC1 as expected and looks good.

**Comment by starksm64** [comment] 2021-10-05 20:46
Releases on GitHub are not automatic, so I created it now.
https://github.com/eclipse-ee4j/injection-api/releases/tag/2.0.1.RC1

**Closed as completed by starksm64** 2021-10-05 20:46 UTC
